class_name ScenarioData
extends RefCounted
## Progressão visual dos 50 corre-corre. Cada capítulo tem uma identidade
## arquitetônica, paleta, céu e fauna aérea para o cenário não parecer repetido.

const PROFILES: Array[Dictionary] = [
    {
        "id": "morro_terra",
        "label": "Morro do Sol",
        "chapter": "Favela de terra",
        "street_surface": "dirt",
        "road": Color("#8a6045"),
        "sidewalk": Color("#777067"),
        "curb": Color("#d9a34f"),
        "divider": Color("#b77954"),
        "tile": Color("#655f59"),
        "building": Color("#a75e4d"),
        "building_alt": Color("#d08a4d"),
        "roof": Color("#5b3c3c"),
        "accent": Color("#ffd05a"),
        "sky_top": Color("#3975a4"),
        "sky_horizon": Color("#f4b269"),
        "ground_horizon": Color("#d7875e"),
        "ground_bottom": Color("#5b4a43"),
        "ambient": Color("#b9c9d1"),
        "sun": Color("#ffd08a"),
        "weather": "poeira dourada",
        "aerial": ["urubu", "pombo"],
        "aerial_count": 4,
        "building_style": "favela",
        "landmark": "water_tank"
    },
    {
        "id": "bairro_residencial",
        "label": "Rua de Bairro",
        "chapter": "Bairro residencial",
        "street_surface": "asphalt",
        "road": Color("#3f4a55"),
        "sidewalk": Color("#a39e8f"),
        "curb": Color("#e5c45f"),
        "divider": Color("#c4775c"),
        "tile": Color("#858176"),
        "building": Color("#e4b779"),
        "building_alt": Color("#82aeb0"),
        "roof": Color("#8a4e3c"),
        "accent": Color("#5bb9c1"),
        "sky_top": Color("#55afd1"),
        "sky_horizon": Color("#ffd28a"),
        "ground_horizon": Color("#d6bb83"),
        "ground_bottom": Color("#45505a"),
        "ambient": Color("#c7dbe0"),
        "sun": Color("#ffe0a4"),
        "weather": "manhã clara",
        "aerial": ["pombo", "passaro"],
        "aerial_count": 3,
        "building_style": "house",
        "landmark": "clothesline"
    },
    {
        "id": "centro_historico",
        "label": "Centro da Cidade",
        "chapter": "Centro e comércio antigo",
        "street_surface": "cobble",
        "road": Color("#4b4c50"),
        "sidewalk": Color("#b8a58c"),
        "curb": Color("#d9be62"),
        "divider": Color("#9d6b57"),
        "tile": Color("#8d7e72"),
        "building": Color("#c56d55"),
        "building_alt": Color("#6c87a3"),
        "roof": Color("#674958"),
        "accent": Color("#f1c555"),
        "sky_top": Color("#5e9ec0"),
        "sky_horizon": Color("#f6b875"),
        "ground_horizon": Color("#b88b70"),
        "ground_bottom": Color("#353d49"),
        "ambient": Color("#c5d0d2"),
        "sun": Color("#ffd28b"),
        "weather": "fim de tarde",
        "aerial": ["pombo", "drone"],
        "aerial_count": 4,
        "building_style": "center",
        "landmark": "storefront"
    },
    {
        "id": "bairro_humilde",
        "label": "Bairro Humilde",
        "chapter": "Bairro humilde e obras",
        "street_surface": "asphalt",
        "road": Color("#404952"),
        "sidewalk": Color("#9d9585"),
        "curb": Color("#e1ae51"),
        "divider": Color("#bd6d56"),
        "tile": Color("#79756d"),
        "building": Color("#b87055"),
        "building_alt": Color("#d3a05d"),
        "roof": Color("#55434a"),
        "accent": Color("#ea7959"),
        "sky_top": Color("#477b9f"),
        "sky_horizon": Color("#db956d"),
        "ground_horizon": Color("#9c7164"),
        "ground_bottom": Color("#303a46"),
        "ambient": Color("#abbfc6"),
        "sun": Color("#ffbd7e"),
        "weather": "nublado quente",
        "aerial": ["pombo", "urubu", "drone"],
        "aerial_count": 4,
        "building_style": "humble",
        "landmark": "construction"
    },
    {
        "id": "classe_media",
        "label": "Bairro Jardim",
        "chapter": "Bairro de classe média",
        "street_surface": "asphalt",
        "road": Color("#3d4855"),
        "sidewalk": Color("#b2ad9f"),
        "curb": Color("#d7c366"),
        "divider": Color("#9c927e"),
        "tile": Color("#938e82"),
        "building": Color("#ded4bb"),
        "building_alt": Color("#9bb8bd"),
        "roof": Color("#6b5c55"),
        "accent": Color("#6dd0bd"),
        "sky_top": Color("#4eacd2"),
        "sky_horizon": Color("#ffe0a1"),
        "ground_horizon": Color("#b9c18f"),
        "ground_bottom": Color("#39434e"),
        "ambient": Color("#d1e3e2"),
        "sun": Color("#ffe3b0"),
        "weather": "sol confortável",
        "aerial": ["passaro", "drone"],
        "aerial_count": 3,
        "building_style": "condo",
        "landmark": "garden"
    },
    {
        "id": "militar_civico",
        "label": "Vila Cívica",
        "chapter": "Bairro militar",
        "street_surface": "asphalt",
        "road": Color("#39474a"),
        "sidewalk": Color("#989a87"),
        "curb": Color("#d9bb59"),
        "divider": Color("#78806b"),
        "tile": Color("#727a6f"),
        "building": Color("#687961"),
        "building_alt": Color("#b9a770"),
        "roof": Color("#4c5b4d"),
        "accent": Color("#e7c84f"),
        "sky_top": Color("#405f87"),
        "sky_horizon": Color("#efaa72"),
        "ground_horizon": Color("#879a86"),
        "ground_bottom": Color("#2e3c42"),
        "ambient": Color("#b7d0cf"),
        "sun": Color("#ffc789"),
        "weather": "bandeira ao vento",
        "aerial": ["drone", "passaro"],
        "aerial_count": 3,
        "building_style": "military",
        "landmark": "guard_post"
    },
    {
        "id": "religioso",
        "label": "Largo da Fé",
        "chapter": "Bairro religioso",
        "street_surface": "cobble",
        "road": Color("#5a5556"),
        "sidewalk": Color("#b5a99a"),
        "curb": Color("#dfc064"),
        "divider": Color("#a97861"),
        "tile": Color("#8f8179"),
        "building": Color("#d8a46d"),
        "building_alt": Color("#8e7190"),
        "roof": Color("#6c4f55"),
        "accent": Color("#c66cb0"),
        "sky_top": Color("#665d9d"),
        "sky_horizon": Color("#f0a778"),
        "ground_horizon": Color("#ad8a7e"),
        "ground_bottom": Color("#3e3c4e"),
        "ambient": Color("#d0c7d7"),
        "sun": Color("#ffd19a"),
        "weather": "sinos ao entardecer",
        "aerial": ["pombo", "passaro"],
        "aerial_count": 4,
        "building_style": "religious",
        "landmark": "church"
    },
    {
        "id": "comercial",
        "label": "Avenida do Comércio",
        "chapter": "Bairro comercial",
        "street_surface": "asphalt",
        "road": Color("#333d4b"),
        "sidewalk": Color("#9c9a93"),
        "curb": Color("#e2bd50"),
        "divider": Color("#d17a54"),
        "tile": Color("#777a7c"),
        "building": Color("#557ea0"),
        "building_alt": Color("#d16b50"),
        "roof": Color("#3d4d62"),
        "accent": Color("#f26a7b"),
        "sky_top": Color("#243d70"),
        "sky_horizon": Color("#e27c71"),
        "ground_horizon": Color("#6b5d67"),
        "ground_bottom": Color("#252e3d"),
        "ambient": Color("#abbfd1"),
        "sun": Color("#ffb572"),
        "weather": "letreiros acesos",
        "aerial": ["drone", "pombo", "aviao"],
        "aerial_count": 5,
        "building_style": "commercial",
        "landmark": "market"
    },
    {
        "id": "turistico",
        "label": "Orla Brasileira",
        "chapter": "Bairro turístico",
        "street_surface": "asphalt",
        "road": Color("#46525a"),
        "sidewalk": Color("#d5c39d"),
        "curb": Color("#e9c95b"),
        "divider": Color("#c68666"),
        "tile": Color("#c5b085"),
        "building": Color("#f0c679"),
        "building_alt": Color("#72b1ad"),
        "roof": Color("#d87351"),
        "accent": Color("#53cbd2"),
        "sky_top": Color("#45bfe0"),
        "sky_horizon": Color("#ffe49a"),
        "ground_horizon": Color("#8bd0c0"),
        "ground_bottom": Color("#3d5a63"),
        "ambient": Color("#d6eef0"),
        "sun": Color("#ffe7ad"),
        "weather": "brisa da praia",
        "aerial": ["gaivota", "aviao", "pombo"],
        "aerial_count": 5,
        "building_style": "tourist",
        "landmark": "kiosk"
    },
    {
        "id": "terminal_final",
        "label": "Terminal Brasil",
        "chapter": "Ponto final e skyline",
        "street_surface": "asphalt",
        "road": Color("#202a3a"),
        "sidewalk": Color("#777d89"),
        "curb": Color("#f3c94d"),
        "divider": Color("#5cc8c4"),
        "tile": Color("#4f596a"),
        "building": Color("#344b70"),
        "building_alt": Color("#795b86"),
        "roof": Color("#27354e"),
        "accent": Color("#6fffe3"),
        "sky_top": Color("#121d46"),
        "sky_horizon": Color("#ca5f79"),
        "ground_horizon": Color("#494468"),
        "ground_bottom": Color("#151e31"),
        "ambient": Color("#9eb6d0"),
        "sun": Color("#ffad86"),
        "weather": "luzes da madrugada",
        "aerial": ["drone", "aviao", "pombo"],
        "aerial_count": 6,
        "building_style": "terminal",
        "landmark": "terminal"
    }
]

static func get_profile(index: int) -> Dictionary:
    var chapter: int = clampi(int(float(index) / 5.0), 0, PROFILES.size() - 1)
    var profile: Dictionary = PROFILES[chapter].duplicate(true)
    profile["chapter_index"] = chapter
    profile["phase_index"] = index
    return profile

static func chapter_name(index: int) -> String:
    return str(get_profile(index).get("chapter", "Brasil"))
